name: xdm-visualization
on:
  workflow_dispatch:
    inputs:
      repoBranch:
        description: 'XDM Repo Branch name'
        required: true
        default: 'master'
      repoHttpsUrl:
        description: 'XDM Repo HTTPS URL'
        required: true
        default: 'https://github.com/adobe/xdm.git'

jobs:
  xdm-visualization:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.13'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - run: bundle install
      - run: npm install -g grunt-cli
      - run: npm install
      - run: ./scripts/xdmVisual4Git.sh ${{ github.event.inputs.repoBranch }} ${{ github.event.inputs.repoHttpsUrl }}

